[package]
name = "elevator_coding"
version = "1.0.0"
build = "build.rs"

[dependencies]
floating-duration = "0.1.2"
termion = "1.0"
timebomb = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
libc = "0.2"
